language: python
python:
  - '3.6'
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info --all
  - conda env create --file environment.yml
  - conda activate ose3dprinter
  - export PYTHONPATH=$PYTHONPATH:$CONDA_PREFIX/lib
script:
    - osewb test
    - osewb lint
    - osewb docs
after_success:
    - coveralls
